def define_schema(cls):
    return IO.Schema(node_id='TripoTextToModelNode', display_name='Tripo: Text to Model', category='api node/3d/Tripo', inputs=[IO.String.Input('prompt', multiline=True), IO.String.Input('negative_prompt', multiline=True, optional=True), IO.Combo.Input('model_version', options=TripoModelVersion, default=TripoModelVersion.v2_5_20250123, optional=True), IO.Combo.Input('style', options=TripoStyle, default='None', optional=True), IO.Boolean.Input('texture', default=True, optional=True), IO.Boolean.Input('pbr', default=True, optional=True), IO.Int.Input('image_seed', default=42, optional=True, advanced=True), IO.Int.Input('model_seed', default=42, optional=True, advanced=True), IO.Int.Input('texture_seed', default=42, optional=True, advanced=True), IO.Combo.Input('texture_quality', default='standard', options=['standard', 'detailed'], optional=True, advanced=True), IO.Int.Input('face_limit', default=-1, min=-1, max=2000000, optional=True, advanced=True), IO.Boolean.Input('quad', default=False, optional=True, advanced=True), IO.Combo.Input('geometry_quality', default='standard', options=['standard', 'detailed'], optional=True, advanced=True)], outputs=[IO.String.Output(display_name='model_file'), IO.Custom('MODEL_TASK_ID').Output(display_name='model task_id'), IO.File3DGLB.Output(display_name='GLB')], hidden=[IO.Hidden.auth_token_comfy_org, IO.Hidden.api_key_comfy_org, IO.Hidden.unique_id], is_api_node=True, is_output_node=True, price_badge=IO.PriceBadge(depends_on=IO.PriceBadgeDepends(widgets=['model_version', 'style', 'texture', 'pbr', 'quad', 'texture_quality', 'geometry_quality']), expr='\n            (\n                $isV14 := $contains(widgets.model_version,"v1.4");\n                $style := widgets.style;\n                $hasStyle := ($style != "" and $style != "none");\n                $withTexture := widgets.texture or widgets.pbr;\n                $isHdTexture := (widgets.texture_quality = "detailed");\n                $isDetailedGeometry := (widgets.geometry_quality = "detailed");\n                $baseCredits :=\n                $isV14 ? 20 : ($withTexture ? 20 : 10);\n                $credits :=\n                $baseCredits\n                + ($hasStyle ? 5 : 0)\n                + (widgets.quad ? 5 : 0)\n                + ($isHdTexture ? 10 : 0)\n                + ($isDetailedGeometry ? 20 : 0);\n                {"type":"usd","usd": $round($credits * 0.01, 2)}\n            )\n            '))

    @classmethod
    async def execute(cls, prompt: str, negative_prompt: str | None=None, model_version=None, style: str | None=None, texture: bool | None=None, pbr: bool | None=None, image_seed: int | None=None, model_seed: int | None=None, texture_seed: int | None=None, texture_quality: str | None=None, geometry_quality: str | None=None, face_limit: int | None=None, quad: bool | None=None) -> IO.NodeOutput:
        style_enum = None if style == 'None' else style
        if not prompt:
            raise RuntimeError('Prompt is required')
        response = await sync_op(cls, endpoint=ApiEndpoint(path='/proxy/tripo/v2/openapi/task', method='POST'), response_model=TripoTaskResponse, data=TripoTextToModelRequest(type=TripoTaskType.TEXT_TO_MODEL, prompt=prompt, negative_prompt=negative_prompt if negative_prompt else None, model_version=model_version, style=style_enum, texture=texture, pbr=pbr, image_seed=image_seed, model_seed=model_seed, texture_seed=texture_seed, texture_quality=texture_quality, face_limit=face_limit if face_limit != -1 else None, geometry_quality=geometry_quality, auto_size=True, quad=quad))
        return await poll_until_finished(cls, response, average_duration=80)