def test_forward_pass_single_state(self):
    sequence = np.ones((1, 2, 3))
    layer = layers.RNN(OneStateRNNCell(2), return_sequences=False)
    output = layer(sequence)
    self.assertAllClose(np.array([[9.0, 9.0]]), output)
    layer = layers.RNN(OneStateRNNCell(2), return_sequences=True)
    output = layer(sequence)
    self.assertAllClose(np.array([[[3.0, 3.0], [9.0, 9.0]]]), output)
    layer = layers.RNN(OneStateRNNCell(2), return_sequences=False, return_state=True)
    (output, state) = layer(sequence)
    self.assertAllClose(np.array([[9.0, 9.0]]), output)
    self.assertAllClose(np.array([[9.0, 9.0]]), state)
    layer = layers.RNN(OneStateRNNCell(2), return_sequences=True, return_state=True)
    (output, state) = layer(sequence)
    self.assertAllClose(np.array([[[3.0, 3.0], [9.0, 9.0]]]), output)
    self.assertAllClose(np.array([[9.0, 9.0]]), state)