def test_statefulness_single_state(self):
    sequence = np.ones((1, 2, 3))
    layer = layers.RNN(OneStateRNNCell(2), stateful=True)
    layer(sequence)
    output = layer(sequence)
    self.assertAllClose(np.array([[45.0, 45.0]]), output)
    layer = layers.RNN(OneStateRNNCell(2), stateful=True, return_state=True)
    layer(sequence)
    (output, state) = layer(sequence)
    self.assertAllClose(np.array([[45.0, 45.0]]), output)
    self.assertAllClose(np.array([[45.0, 45.0]]), state)