def test_forward_pass_two_states(self):
    sequence = np.ones((1, 2, 3))
    layer = layers.RNN(TwoStatesRNNCell(2), return_sequences=False)
    output = layer(sequence)
    self.assertAllClose(np.array([[18.0, 18.0]]), output)
    layer = layers.RNN(TwoStatesRNNCell(2), return_sequences=True)
    output = layer(sequence)
    self.assertAllClose(np.array([[[6.0, 6.0], [18.0, 18.0]]]), output)
    layer = layers.RNN(TwoStatesRNNCell(2), return_sequences=False, return_state=True)
    (output, state1, state2) = layer(sequence)
    self.assertAllClose(np.array([[18.0, 18.0]]), output)
    self.assertAllClose(np.array([[9.0, 9.0]]), state1)
    self.assertAllClose(np.array([[9.0, 9.0]]), state2)
    layer = layers.RNN(TwoStatesRNNCell(2), return_sequences=True, return_state=True)
    (output, state1, state2) = layer(sequence)
    self.assertAllClose(np.array([[[6.0, 6.0], [18.0, 18.0]]]), output)
    self.assertAllClose(np.array([[9.0, 9.0]]), state1)
    self.assertAllClose(np.array([[9.0, 9.0]]), state2)