@pytest.mark.requires_trainable_backend
def test_basics(self):
    self.run_layer_test(layers.RNN, init_kwargs={'cell': OneStateRNNCell(5, state_size=5)}, input_shape=(3, 2, 4), expected_output_shape=(3, 5), expected_num_trainable_weights=2, expected_num_non_trainable_weights=0, expected_num_seed_generators=0, supports_masking=True)
    self.run_layer_test(layers.RNN, init_kwargs={'cell': OneStateRNNCell(5, state_size=[5])}, input_shape=(3, 2, 4), expected_output_shape=(3, 5), expected_num_trainable_weights=2, expected_num_non_trainable_weights=0, expected_num_seed_generators=0, supports_masking=True)
    self.run_layer_test(layers.RNN, init_kwargs={'cell': OneStateRNNCell(5, state_size=(5,))}, input_shape=(3, 2, 4), expected_output_shape=(3, 5), expected_num_trainable_weights=2, expected_num_non_trainable_weights=0, expected_num_seed_generators=0, supports_masking=True)
    self.run_layer_test(layers.RNN, init_kwargs={'cell': OneStateRNNCell(5), 'return_sequences': True}, input_shape=(3, 2, 4), expected_output_shape=(3, 2, 5), expected_num_trainable_weights=2, expected_num_non_trainable_weights=0, expected_num_seed_generators=0, supports_masking=True)
    self.run_layer_test(layers.RNN, init_kwargs={'cell': OneStateRNNCell(5), 'go_backwards': True, 'unroll': True}, input_shape=(3, 2, 4), expected_output_shape=(3, 5), expected_num_trainable_weights=2, expected_num_non_trainable_weights=0, expected_num_seed_generators=0, supports_masking=True)
    self.run_layer_test(layers.RNN, init_kwargs={'cell': TwoStatesRNNCell(5, state_size=[5, 5])}, input_shape=(3, 2, 4), expected_output_shape=(3, 5), expected_num_trainable_weights=3, expected_num_non_trainable_weights=0, expected_num_seed_generators=0, supports_masking=True)
    self.run_layer_test(layers.RNN, init_kwargs={'cell': TwoStatesRNNCell(5, state_size=(5, 5))}, input_shape=(3, 2, 4), expected_output_shape=(3, 5), expected_num_trainable_weights=3, expected_num_non_trainable_weights=0, expected_num_seed_generators=0, supports_masking=True)
    self.run_layer_test(layers.RNN, init_kwargs={'cell': TwoStatesRNNCell(5), 'return_sequences': True}, input_shape=(3, 2, 4), expected_output_shape=(3, 2, 5), expected_num_trainable_weights=3, expected_num_non_trainable_weights=0, expected_num_seed_generators=0, supports_masking=True)